BootcampFinal/Controllers/ResidentHouseController.cs
using BootcampFinal.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using X.PagedList;

namespace BootcampFinal.Controllers
{
    [Authorize("Administrator")]
    public class ResidentHouseController : Controller
    {
        private readonly ModelContext _db;

        public ResidentHouseController(ModelContext db)
        {
            _db = db;
        }

        public IActionResult Index(int page =1, string search = "")
        {
            
            var rh = _db.UserFlats.AsQueryable();

            if (search != null)
            {
                rh = _db.UserFlats.Where(x => x.BuildingFlat.Building.Name.Contains(search) || x.BuildingFlat.FlatType.Name.Contains(search) || x.BuildingFlat.Flat.Name.Contains(search));

                ViewBag.search = search;
                ViewBag.count = rh.Count();
            }

            rh = rh.OrderBy(x => x.Id);
            ViewBag.page = page;
            ViewBag.user = _db.Users.Where(x => x.UserRole == UserRole.Resident).ToList();
            ViewBag.bf = _db.BuildingFlats.ToList();
            return View(rh.ToPagedList(page,10));
        }

        [HttpPost]
        public IActionResult AddRH(UserFlat userFlat)
        {
            if(userFlat != null)
            {
                _db.UserFlats.Add(userFlat);
                _db.SaveChanges();
            }
            return RedirectToAction("Index");
        }

        public JsonResult GetRH(int id)
        {
            var rh = _db.UserFlats.Select(x => new UserFlat { Id = x.Id, BuildingFlatId = x.BuildingFlatId, PaymentId = x.PaymentId, UserId = x.UserId }).FirstOrDefault(n => n.Id == id);
            return Json(rh);
        }

        [HttpPost]
        public async Task<IActionResult> EditRH(UserFlat userFlat)
        {
            var rh = _db.UserFlats.FirstOrDefault(x => x.Id == userFlat.Id);

            if(rh != null)
            {
                rh.BuildingFlatId = userFlat.BuildingFlatId;
                rh.PaymentId = userFlat.PaymentId;
                rh.UserId = userFlat.UserId;

                if (ModelState.IsValid)
                {
                    await _db.SaveChangesAsync();
                }
            }
            return RedirectToAction("Index");
        }

        [HttpPost]
        public async Task<IActionResult> DeleteRH(int id)
        {
            var rh = _db.UserFlats.FirstOrDefault(x => x.Id == id);

            if(rh != null)
            {
                _db.Remove(rh);
                await _db.SaveChangesAsync();
            }
            return RedirectToAction("Index");
        }
    }
}

BootcampFinal/Views/ResidentHouse/Index.cshtml
@model IPagedList<BootcampFinal.Models.UserFlat>

@{
    Layout = "~/Views/Shared/AdminLTE/_Layout.cshtml"; ;
}

<button type="button" class="btn btn-success row" data-toggle="modal" data-target="#addRHModal">
    Append resident to flat 
</button>
<form class="form-inline float-right" method="get">
    <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search" name="search" value="@ViewBag.search">
    <button class="btn btn-primary" type="submit">Search</button>
</form>

@if (TempData["message"] != null)
{
    NotificationViewModel message = NotificationViewModel.GetNotificationFromJson(TempData["message"].ToString());

    <div class="mt-4 card margin-top bg-gradient-@message.NotificationType.ToString()">
        <div class="card-header">
            <h3 class="card-title">@message.Title</h3>

            <div class="card-tools">
                <button type="button" class="btn btn-tool" data-card-widget="remove">
                    <i class="fas fa-times"></i>
                </button>
            </div>
            <!-- /.card-tools -->
        </div>
        <!-- /.card-header -->
        <div class="card-body">
            @message.Content
        </div>
        <!-- /.card-body -->
    </div>
}

@if (ViewBag.search != null)
{
    <div class="mt-4 card margin-top bg-gradient-info">
        <div class="card-header">
            <h3 class="card-title">Search Results</h3>

            <div class="card-tools">
                <button type="button" class="btn btn-tool" data-card-widget="remove">
                    <i class="fas fa-times"></i>
                </button>
            </div>
            <!-- /.card-tools -->
        </div>
        <!-- /.card-header -->
        <div class="card-body">
            @Html.ActionLink("Clear Search", "Index", "ResidentHouse", null, new { @class = "btn btn-sm btn-default mt-2" })
        </div>
        <!-- /.card-body -->
    </div>
}

<div class="card card-primary mt-4">
    <div class="card-header">
        <b>House List</b>
    </div>

    <table class="table table-hover table-bordered table-striped">

        <thead>
            <tr>
                <th style="width:6%">#.</th>
                <th>Resident</th>
                <th>Building</th>
                <th>No</th>
                <th>Flat Type</th>
                <th class="text-right" style="width:10%">İşlem</th>
            </tr>
        </thead>

        <tbody>
            @{
                int page = ((int)ViewBag.page);
                int counter = (page - 1) * 10;
            }

            @foreach (var item in Model)
            {
                counter++;
                <tr>
                    <td>@counter.</td>
                    <td>@item.User.Name @item.User.LastName</td>
                    <td>@item.BuildingFlat.Building.Name</td>
                    <td>@item.BuildingFlat.Flat.Name</td>
                    <td>@item.BuildingFlat.FlatType.Name</td>
                    <td>
                        <button type="button" class="btn btn-sm btn-warning editBtn" data-toggle="modal" data-target="#editResidentHouseModal" data-id="@item.Id">Edit</button>
                        <button type="button" class="btn btn-sm btn-danger editBtn" data-toggle="modal" data-target="#deleteResidentHouseModal" data-id="@item.Id">Delete</button>
                    </td>
                </tr>
            }
        </tbody>

    </table>

    <div class="col-md-12">
        <div class="float-right">
            @Html.PagedListPager(Model, page => Url.Action("Index", new { page, search = ViewBag.search }), new PagedListRenderOptions
       {
           LiElementClasses = new string[] { "page-item" },
           PageClasses = new string[] { "page-link", "text-bold" },
           DisplayLinkToFirstPage = PagedListDisplayMode.Always,
           DisplayLinkToLastPage = PagedListDisplayMode.Always,
           DisplayLinkToNextPage = PagedListDisplayMode.Always,
           DisplayLinkToPreviousPage = PagedListDisplayMode.Always,
           DisplayLinkToIndividualPages = true
       })
        </div>
    </div>
</div>



<!-- ADD -->

<div class="modal fade" tabindex="-1" role="dialog" id="addRHModal">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Add new house</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form asp-controller="ResidentHouse" asp-action="AddRH" method="post">

                    <div class="form-group">
                        <label for="Building">Resident:</label>
                        <select class="form-control UserId" name="UserId">
                            <option value="0">Select a Resident</option>
                            @foreach (var item in (List<User>)ViewBag.user)
                            {
                                <option value="@item.Id">@item.Name</option>
                            }
                        </select>
                    </div>

                    <div class="form-group">
                        <label for="Building">Flat:</label>
                        <select class="form-control BuildingFlatId" name="BuildingFlatId">
                            <option value="0">Select a Resident</option>
                            @foreach (var item in (List<BuildingFlat>) ViewBag.bf)
                            {
                               <option value="@item.Id">@item.Building.Name @item.Flat.Name</option>
                            }
                        </select>
                    </div>
                    <div class="form-group">
                        <input type="submit" class="btn btn-success" />
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <i>
                    Açıklama yazılacak
                </i>
            </div>
        </div>
    </div>
</div>

<!-- EDIT -->

<div class="modal fade" tabindex="-1" role="dialog" id="editResidentHouseModal">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Add new house</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form asp-controller="ResidentHouse" asp-action="EditRH" method="post">
                    <input type="hidden" id="Id" name="Id" />
                    <div class="form-group">
                        <label for="Building">Resident:</label>
                        <select class="form-control UserId" name="UserId">
                            <option value="0">Select a Resident</option>
                            @foreach (var item in (List<User>)ViewBag.user)
                            {
                                <option value="@item.Id">@item.Name</option>
                            }
                        </select>
                    </div>

                    <div class="form-group">
                        <label for="Building">Flat:</label>
                        <select class="form-control BuildingFlatId" name="BuildingFlatId">
                            <option value="0">Select a Resident</option>
                            @foreach (var item in (List<BuildingFlat>)ViewBag.bf)
                            {
                                <option value="@item.Id">@item.Building.Name @item.Flat.Name</option>
                            }
                        </select>
                    </div>

                    <div class="form-group">
                        <input type="submit" class="btn btn-success" />
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <i>
                    Açıklama yazılacak
                </i>
            </div>
        </div>
    </div>
</div>


<!-- DELETE -->

<div class="modal fade" tabindex="-1" role="dialog" id="deleteResidentHouseModal">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Add new house</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form asp-controller="ResidentHouse" asp-action="DeleteRH" method="post">
                    <input type="hidden" id="Id" name="Id" />

                    <div class="form-group">
                        <label for="Building">Resident:</label>
                        <select class="form-control UserId" name="UserId" disabled>
                            <option value="0">Select a Resident</option>
                            @foreach (var item in (List<User>)ViewBag.user)
                            {
                                <option value="@item.Id">@item.Name</option>
                            }
                        </select>
                    </div>

                    <div class="form-group">
                        <label for="Building">Flat:</label>
                        <select class="form-control BuildingFlatId" name="BuildingFlatId" disabled>
                            <option value="0">Select a Resident</option>
                            @foreach (var item in (List<BuildingFlat>)ViewBag.bf)
                            {
                                <option value="@item.Id">@item.Building.Name @item.Flat.Name</option>
                            }
                        </select>
                    </div>

                    <div class="form-group">
                        <input type="submit" class="btn btn-danger" value="Delete" />
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <i>
                    Açıklama yazılacak
                </i>
            </div>
        </div>
    </div>
</div>

@section Scripts{
    <script type="text/javascript">
        $(function () {
            $(".editBtn").on("click", function () {
                var RHId = $(this).data("id");
                var getRHUrl = "@Url.Action("GetRH", "ResidentHouse", null, "http")";
                var fullUrl = getRHUrl + "/" + RHId;

                $.get(fullUrl, function (data, status) {
                    $("select.UserId").val(data.userId); 
                    
                    $("select.BuildingFlatId").val(data.buildingFlatId);
                    $("input#Id").val(data.id);

                    alert(data.userId + data.buildingFlatId);
                });

            })
        })
    </script>
} 